pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Define build steps here
                sh 'mvn clean test package'
            }
        }
        stage('Test') {
            steps {
                // Define test steps here
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                // Define deployment steps here
                sh 'mvn deploy'
            }
        }
    }
}
